const { DataTypes } = require("sequelize");
const { sequelize } = require("../sequelize");
const Server = require("./server");
const Emojis = require("../../Emojis.json");
const { redisClient, getFilaConfigKey } = require("../../utils/cache");

const FilaConfig = sequelize.define(
  "FilaConfig",
  {
    guildId: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
      references: { model: Server, key: "guildId" },
      onDelete: "CASCADE",
    },
    coinsWinner: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      allowNull: false,
    },
    coinsLoser: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      allowNull: false,
    },
    modalidades: {
      type: DataTypes.JSON,
      allowNull: true,
      defaultValue: [
        {
          id: "1v1_mobile",
          nome: "1v1 Mobile",
          canalId: null,
          ativo: true,
          emoji: Emojis.mobile,
          valores: [],
          botoes: ["Gelo Normal", "Gelo Infinito"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "2v2_mobile",
          nome: "2v2 Mobile",
          canalId: null,
          ativo: true,
          emoji: Emojis.mobile,
          valores: [],
          botoes: ["Entrar na Fila", "Ump e Xm8"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "3v3_mobile",
          nome: "3v3 Mobile",
          canalId: null,
          ativo: true,
          emoji: Emojis.mobile,
          valores: [],
          botoes: ["Entrar na Fila", "Ump e Xm8"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "4v4_mobile",
          nome: "4v4 Mobile",
          canalId: null,
          ativo: true,
          emoji: Emojis.mobile,
          valores: [],
          botoes: ["Entrar na Fila", "Ump e Xm8"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
         {
          id: "1v1_mobilador",
          nome: "1v1 Mobilador",
          canalId: null,
          ativo: true,
          emoji: Emojis.mobilador,
          valores: [],
          botoes: ["Gelo Normal", "Gelo Infinito"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "2v2_mobilador",
          nome: "2v2 Mobilador",
          canalId: null,
          ativo: true,
          emoji: Emojis.mobilador,
          valores: [],
          botoes: ["Mobilador"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "3v3_mobilador",
          nome: "3v3 Mobilador",
          canalId: null,
          ativo: true,
          emoji: Emojis.mobilador,
          valores: [],
          botoes: ["Mobilador"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "4v4_mobilador",
          nome: "4v4 Mobilador",
          canalId: null,
          ativo: true,
          emoji: Emojis.mobilador,
          valores: [],
          botoes: ["Mobilador"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "1v1_emu",
          nome: "1v1 Emulador",
          canalId: null,
          ativo: true,
          emoji: Emojis.laptop,
          valores: [],
          botoes: ["Gelo Normal", "Gelo Infinito"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "2v2_emu",
          nome: "2v2 Emulador",
          canalId: null,
          ativo: true,
          emoji: Emojis.laptop,
          valores: [],
          botoes: ["Entrar na Fila", "Ump e Xm8"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "3v3_emu",
          nome: "3v3 Emulador",
          canalId: null,
          ativo: true,
          emoji: Emojis.laptop,
          valores: [],
          botoes: ["Entrar na Fila", "Ump e Xm8"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "4v4_emu",
          nome: "4v4 Emulador",
          canalId: null,
          ativo: true,
          emoji: Emojis.laptop,
          valores: [],
          botoes: ["Entrar na Fila", "Ump e Xm8"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "1v1_misto",
          nome: "1v1 Misto",
          canalId: null,
          ativo: false,
          emoji: Emojis.mix,
          valores: [],
          botoes: [],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "2v2_misto",
          nome: "2v2 Misto",
          canalId: null,
          ativo: true,
          emoji: Emojis.mix,
          valores: [],
          botoes: ["1 Emu"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "3v3_misto",
          nome: "3v3 Misto",
          canalId: null,
          ativo: true,
          emoji: Emojis.mix,
          valores: [],
          botoes: ["2 Emu"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "4v4_misto",
          nome: "4v4 Misto",
          canalId: null,
          ativo: true,
          emoji: Emojis.mix,
          valores: [],
          botoes: ["3 Emu"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "1v1_tatico",
          nome: "1v1 Tático",
          canalId: null,
          ativo: false,
          emoji: Emojis.boxglove,
          valores: [],
          botoes: ["Mobile", "Emulador", "Misto"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "2v2_tatico",
          nome: "2v2 Tático",
          canalId: null,
          ativo: false,
          emoji: Emojis.boxglove,
          valores: [],
          botoes: ["Mobile", "Emulador", "Misto"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "3v3_tatico",
          nome: "3v3 Tático",
          canalId: null,
          ativo: false,
          emoji: Emojis.boxglove,
          valores: [],
          botoes: ["Mobile", "Emulador", "Misto"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "4v4_tatico",
          nome: "4v4 Tático",
          canalId: null,
          ativo: false,
          emoji: Emojis.boxglove,
          valores: [],
          botoes: ["Mobile", "Emulador", "Misto"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "1v1_classico",
          nome: "1v1 Clássico",
          canalId: null,
          ativo: false,
          emoji: Emojis.royale,
          valores: [],
          botoes: ["Entrar na Fila"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "2v2_classico",
          nome: "2v2 Clássico",
          canalId: null,
          ativo: false,
          emoji: Emojis.royale,
          valores: [],
          botoes: ["Entrar na Fila"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "1v1_estrategiatripla",
          nome: "1v1 Estratégia Tripla",
          canalId: null,
          ativo: false,
          emoji: Emojis.royale,
          valores: [],
          botoes: ["Entrar na Fila"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
        {
          id: "2v2_estrategiatripla",
          nome: "2v2 Estratégia Tripla",
          canalId: null,
          ativo: false,
          emoji: Emojis.royale,
          valores: [],
          botoes: ["Entrar na Fila"],
          templateDescription:
            "### [[modo_jogo]]\n**Valor:** [[valor_partida]]\n**Jogadores:**\n[[jogadores_fila]]",
          templateAvatarUrl: null,
          templateAvatarUrl: null,
          templateBannerUrl: null,
          templateColor: "#e89b00",
          templateFooter: null,
          templateFooterIconUrl: null,
        },
      ],
    },
  },
  {
    tableName: "configs_filas",
    timestamps: false,

    hooks: {
      afterSave: async (instance, options) => {
        if (!redisClient || !redisClient.isReady) return;
        try {
          const cacheKey = getFilaConfigKey(instance.guildId);
          await redisClient.set(cacheKey, JSON.stringify(instance.toJSON()));
        } catch (err) {
          console.error(
            `[HOOK_FilaConfig] Falha ao atualizar cache ${instance.guildId}:`,
            err
          );
        }
      },
      afterDestroy: async (instance, options) => {
        if (!redisClient || !redisClient.isReady) return;
        try {
          const cacheKey = getFilaConfigKey(instance.guildId);
          await redisClient.del(cacheKey);
        } catch (err) {
          console.error(
            `[HOOK_FilaConfig] Falha ao deletar cache ${instance.guildId}:`,
            err
          );
        }
      },
    },
  }
);

Server.hasOne(FilaConfig, { foreignKey: "guildId", onDelete: "CASCADE" });
FilaConfig.belongsTo(Server, { foreignKey: "guildId", onDelete: "CASCADE" });

module.exports = FilaConfig;